version: '3.8'

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    container_name:  ${DOCKER_PROJECT_NAME}
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CADDY_INGRESS_NETWORKS=caddy_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy_net
    restart: unless-stopped
    labels:
      caddy.global: "http:// { 
        redir https://{host}{uri} permanent
      }"
      com.docker.compose.project: "${DOCKER_PROJECT_NAME}"

  app:
    image: nginx
    container_name: ${DOCKER_PROJECT_NAME}-app
    volumes:
      - ./app:/usr/share/nginx/html
    labels:
      caddy: ${DOMAIN}
      caddy.reverse_proxy: "{{upstreams 80}}"
      com.docker.compose.project: "${DOCKER_PROJECT_NAME}"
    networks:
      - caddy_net

volumes:
  caddy_data:
    name: ${DOCKER_PROJECT_NAME}_caddy_data
  caddy_config:
    name: ${DOCKER_PROJECT_NAME}_caddy_config

networks:
  caddy_net:
    external: true