version: '3.8'

services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:2
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CADDY_INGRESS_NETWORKS=caddy_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy_net
    restart: unless-stopped
    labels:
      # Global redirect to HTTPS
      caddy.global: "http:// { 
        redir https://{host}{uri} permanent
      }"

  app:
    image: nginx
    container_name: ${DOCKER_PROJECT_NAME}
    volumes:
      - ./app:/usr/share/nginx/html
    labels:
      caddy: ${DOMAIN}
      caddy.reverse_proxy: "{{upstreams 80}}"
    networks:
      - caddy_net

volumes:
  caddy_data:
  caddy_config:

networks:
  caddy_net:
    external: true