# Global configuration
global:
  checkNewVersion: true
  sendAnonymousUsage: false

# Entry points configuration
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt

# SSL configuration with Let's Encrypt
certificatesResolvers:
  letsencrypt:
    acme:
      email: ${EMAIL}
      storage: "/acme.json"
      httpChallenge:
        entryPoint: web

# Docker provider configuration
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: traefik-proxy

# API and Dashboard configuration
api:
  dashboard: true
  insecure: false

# Log configuration
log:
  level: DEBUG